# Generated by Django 3.1.6 on 2021-02-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='i_am_author',
            field=models.BooleanField(default=False, null=True, verbose_name='Я автор'),
        ),
        migrations.AlterField(
            model_name='author',
            name='active',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=100, verbose_name='Активность'),
        ),
    ]
