# Generated by Django 3.1.6 on 2021-02-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20210215_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='i_am_author',
            field=models.BooleanField(default=False, verbose_name='Я автор'),
        ),
    ]
