# Generated by Django 3.1.6 on 2021-03-05 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_authorinfo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(blank=True, max_length=100, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('genre_name',),
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(blank=True, max_length=100, verbose_name='Издательство')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Ссылка')),
                ('photo1', models.FileField(blank=True, upload_to='media/%Y/%m/%d', verbose_name='Фото1')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
                'ordering': ('publisher_name',),
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_name', models.CharField(blank=True, max_length=100, verbose_name='Имя автора')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Ссылка')),
                ('photo1', models.FileField(blank=True, upload_to='media/%Y/%m/%d', verbose_name='Фото1')),
                ('photo2', models.FileField(blank=True, upload_to='media/%Y/%m/%d', verbose_name='Фото2')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ('writer_name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Ссылка')),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=100, verbose_name='Статус')),
                ('number_of_pages', models.PositiveSmallIntegerField(blank=True, verbose_name='Количество страниц')),
                ('publish_year', models.DateField(blank=True, verbose_name='Год публикации')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('photo1', models.FileField(blank=True, upload_to='media/%Y/%m/%d', verbose_name='Фото1')),
                ('photo2', models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d', verbose_name='Фото2')),
                ('price', models.PositiveSmallIntegerField(blank=True, default='1', verbose_name='Цена')),
                ('discount', models.PositiveSmallIntegerField(blank=True, default='1', verbose_name='Скидка')),
                ('genre_name', models.ManyToManyField(blank=True, to='blog_app.Genre', verbose_name='Жанр')),
                ('maker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('publisher_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.publisher', verbose_name='Издательство')),
                ('writer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.writer', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('-creation_date',),
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
