# Generated by Django 3.1.6 on 2021-02-15 10:58

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20210215_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media//media', location='C:\\1_Python\\Project\\myblog\\blog_pr\\media\\media/'), upload_to='media/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media//media', location='C:\\1_Python\\Project\\myblog\\blog_pr\\media\\media/'), upload_to='media/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media//media', location='C:\\1_Python\\Project\\myblog\\blog_pr\\media\\media/'), upload_to='media/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media//media', location='C:\\1_Python\\Project\\myblog\\blog_pr\\media\\media/'), upload_to='media/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
