# Generated by Django 3.1.6 on 2021-03-10 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_book_genre_publisher_writer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorinfo',
            options={'ordering': ['-reg_date'], 'verbose_name': 'Информация о авторе', 'verbose_name_plural': 'BLOG-Информация о авторах'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-creation_date',), 'verbose_name': 'Книга', 'verbose_name_plural': 'SHOP-Книги'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'BLOG-Категории'},
        ),
        migrations.AlterModelOptions(
            name='commentsauthor',
            options={'ordering': ['author_name'], 'verbose_name': 'Комментарий к автору', 'verbose_name_plural': 'BLOG-Комментарии к автору'},
        ),
        migrations.AlterModelOptions(
            name='commentsnews',
            options={'ordering': ['author_name'], 'verbose_name': 'Комментарий к статье', 'verbose_name_plural': 'BLOG-Комментарии к статьям'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('genre_name',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'SHOP-Жанры'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-create_date', '-change_date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'BLOG-Новости'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ('publisher_name',), 'verbose_name': 'Издательство', 'verbose_name_plural': 'SHOP-Издательства'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'USER-Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='writer',
            options={'ordering': ('writer_name',), 'verbose_name': 'Автор', 'verbose_name_plural': 'SHOP-Авторы'},
        ),
        migrations.CreateModel(
            name='CommentsWriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.writer', verbose_name='Писатель')),
            ],
            options={
                'verbose_name': 'Комментарий к писателю',
                'verbose_name_plural': 'BLOG-Комментарии к писателю',
                'ordering': ['author_name'],
            },
        ),
        migrations.CreateModel(
            name='CommentsBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Комментарий к книге',
                'verbose_name_plural': 'BLOG-Комментарии к книге',
                'ordering': ['author_name'],
            },
        ),
    ]
