# Generated by Django 3.1.6 on 2021-03-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20210310_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentsbook',
            options={'ordering': ['author_name'], 'verbose_name': 'Комментарий к книге', 'verbose_name_plural': 'SHOP-Комментарии к книге'},
        ),
        migrations.AlterModelOptions(
            name='commentswriter',
            options={'ordering': ['author_name'], 'verbose_name': 'Комментарий к писателю', 'verbose_name_plural': 'SHOP-Комментарии к писателю'},
        ),
        migrations.AlterModelManagers(
            name='book',
            managers=[
            ],
        ),
    ]
