# Generated by Django 3.1.6 on 2021-03-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_commentsbook_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsbook',
            name='quality',
            field=models.CharField(choices=[('1', 'Посредственно'), ('2', 'Неудовлетворительно'), ('3', 'Удовлетворительно'), ('4', 'Хорошо'), ('5', 'Отлично')], default='5', max_length=100, verbose_name='Оценка'),
        ),
    ]
