# Generated by Django 3.1.6 on 2021-03-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20210310_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name='Фото1'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d', verbose_name='Фото2'),
        ),
    ]
