# Generated by Django 3.1.6 on 2021-03-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_auto_20210315_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre_name',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publisher_name',
            new_name='publisher',
        ),
    ]
